apiVersion: v1
kind: Service
metadata:
  name: frontend
  labels:
    app: guestbook
    tier: frontend
spec:
  type: LoadBalancer
  ports:
  - name: server
    port: 8080
    targetPort: 8080
  - name: ui
    port: 7000
    targetPort: 7000
  selector:
    app: boxes
    tier: frontend
---
apiVersion: v1
kind: ReplicationController
metadata:
  name: frontend
  labels:
    app: boxes-ui
    tier: frontend
spec:
  replicas: 3
  template:
    metadata:
      labels:
        app: boxes
        tier: frontend
    spec:
      containers:
      - name: boxes
        image: gokskrish/boxes
        ports:
        - containerPort: 7000
      - name: boxes-ui
        image: gokskrish/boxes-ui
        ports:
        - containerPort: 4200
        